name: Build Android APK

on:
  workflow_dispatch:
    inputs:
      merchantId:
        description: 'Merchant ID'
        required: true
        type: string

jobs:
  build:
    name: Build Android Debug APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to gradlew
        run: chmod +x ToDoApp/gradlew

      - name: Build APK (assembleDebug)
        working-directory: ToDoApp
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: ToDoApp-Debug-APK
          path: ToDoApp/app/build/outputs/apk/debug/*.apk
