name: Build iOS (Development)

on:
  workflow_dispatch:
    inputs:
      merchantId:
        description: 'Merchant ID'
        required: true
        type: string

jobs:
  build_ios:
    name: Build iOS Archive
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_15.0.app

      - name: Build Archive
        run: |
          set -e
          cd IOS
          rm -rf build/ || true
          
          # Build archive only (no export)
          xcodebuild -project SideDrawerDemo.xcodeproj \
                     -scheme SideDrawerDemo \
                     -sdk iphoneos \
                     -configuration Debug \
                     -archivePath build/SideDrawerDemo.xcarchive \
                     archive

      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: iOS-Archive
          path: IOS/build/SideDrawerDemo.xcarchive
